# apiVersion: v1
# data:
#   password: UmVmYWVsMzE2NDQ0MDU4
#   username: cmVmYWVsYg==
# kind: Secret
# metadata:
#   name: repo-secret
#   namespace: argocd
# type: Opaque

---
apiVersion: v1
data:
  repositories: |
    - url: https://github.com/refaelb/argo/helm
      type: git
      passwordSecret:
        key: password
        name: repo-secret
      usernameSecret:
        key: username
        name: repo-secret
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd